#! /bin/bash
echo Stranger@1989 | sudo -S systemctl start puppet
echo Stranger@1989 | sudo -S systemctl enable puppet
puppetserver ca list
puppetserver ca sign --certname puppet-agent.novalocal
puppetserver ca list
